/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bird_fly.glb 
Author: xidingvienna (https://sketchfab.com/xidingvienna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lady-bug-bird-5c89639f112e4c4d8c919307cf80c559
Title: Lady Bug Bird
*/

import React, { useEffect, useState } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Birdfly(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/animations/bird_fly.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && actions['Fly and Eye Roll']) {
      const animationAction = actions['Fly and Eye Roll']
      animationAction.reset().fadeIn(1).play()
      animationAction.setEffectiveTimeScale(0.5)  // Slowed down playback to 50% speed

      // Dispatch event to indicate Birdfly is loaded
      window.dispatchEvent(new Event('birdflyLoaded'));
    } else {
      console.warn('Animation not found in actions.')
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          {/* <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0]}> */}
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Bird_Rig_42" rotation={[0, 0.283, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Beak_34" />
                  <group name="Brows_35" />
                  <group name="Bird_36" />
                  <group name="Eyes_37" />
                  <group name="Hair_38" />
                  <group name="Tails_39" />
                  <group name="Tongue_40" />
                  <group name="Wings_41" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Beak} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Feather_Diffuse} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Bird_Body} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.black} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.White_Diffuse} skeleton={nodes.Object_14.skeleton} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Feather_Diffuse} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Feather_Diffuse} skeleton={nodes.Object_18.skeleton} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Tongue} skeleton={nodes.Object_20.skeleton} />
                  <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Feather_Diffuse} skeleton={nodes.Object_22.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    // </group>
  )
}

useGLTF.preload('/animations/bird_fly.glb')
export default Birdfly
