/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/character_animated.glb 
Author: sikoro (https://sketchfab.com/sikorodz05)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/character-animated-5db0241c92644179b33b87a0eaf61f63
Title: Character animated
*/

import React, { useEffect } from 'react';
import { useGraph} from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Character(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/animations/character_animated.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(animations);


  useEffect(() => {
    if (!actions) {
      console.error("No actions available - animations might not be loaded properly");
      return;
    }
    
    const animationName = 'pexels-media-4260697-1677171430630_001_001';
    if (actions[animationName]) {
      const animationAction = actions[animationName];
      animationAction.reset().fadeIn(0.5).play();
    } else {
      console.warn(`Animation "${animationName}" not found. Available animations:`, Object.keys(actions));
    }
  }, [actions]);

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.065}>
          <group name="pexels-media-4260697-1677171430630_001_001_Adult_Male(includeTPose)fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Body" />
                  <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.body1} skeleton={nodes.Object_6.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animations/character_animated.glb')
export default Character
